[project]
name = "fastapi-ecommerce-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BerkAkipek", email = "berk.akipek.96@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosmtplib>=5.1.3",
    "alembic>=1.20.0",
    "asyncmy>=0.2.14",
    "asyncpg>=0.31.0",
    "authlib>=1.8.0",
    "boto3>=1.43.98",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "greenlet>=3.5.6",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "passlib[argon2]>=1.7.4",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.14.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.54",
    "stripe>=15.6.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
fastapi-ecommerce-backend = "fastapi_ecommerce_backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
